name: Publish package to GitHub Packages
on:
  push:
    # branches: ['*']
    branches-ignore:
      - 'main'
    # Publish semver tags as releases.
    tags: ['v*.*.*']

jobs:
  # Push the pacakge.json version to a variable
  package-version:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          node-version: '20.x'
      - name: Get package version
        id: package-version
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
      - name: Echo package version
        run: echo "${{ steps.package-version.outputs.version }}"
    outputs:
      version: ${{ steps.package-version.outputs.version }}
  build:
    needs: package-version
    if: contains(needs.package-version.outputs.version, '-dev')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      # - name: Echo package version
      #   run: echo "${{ needs.package-version.outputs.version }}"
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: 'https://npm.pkg.github.com'
          # Defaults to the user or organization that owns the workflow file
          scope: '@nokkvireyr'
      - run: 'pnpm install --frozen-lockfile'
        env:
          NODE_AUTH_TOKEN: ${{ github.token }}
      - run: pnpm build
      - run: pnpm publish --tag dev
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
